# Cloudflare Pages configuration
name = "lexia-website"
compatibility_date = "2024-08-20"

[build]
command = "npm run build"
cwd = "."
watch_dir = "src"

[env.production]
# Environment variables will be set in Cloudflare dashboard
# RESEND_API_KEY = "your_key_here"

[[kv_namespaces]]
binding = "LEXIA_KV"
preview_id = ""
id = ""