export const authorData = [
  {
    name: "Rafly Kurnia",
    role: "Lead Web Designer",
    bio: "Rafly leads our web design strategy, focusing on innovative and user-centric solutions. With over 10 years in digital, his articles explore cutting-edge design trends and best practices.",
    image: "/team/person-1.png",
    email: "rafly@lexia.design",
    linkedin: "https://www.linkedin.com/company/lexia",
    slug: "rafly-kurnia",
  },
  {
    name: "Maya Wijaya",
    role: "UX/UI Lead",
    bio: "Maya excels in crafting intuitive user experiences. Her articles delve into UX psychology, usability principles, and creating engaging digital interfaces.",
    image: "/team/person-2.png",
    email: "maya@lexia.design",
    linkedin: "https://www.linkedin.com/company/lexia",
    slug: "maya-wijaya",
  },
  {
    name: "Aisha Putri",
    role: "Frontend Development Lead",
    bio: "Aisha heads our frontend development. She writes about modern frontend technologies, responsive design, and web performance optimization.",
    image: "/team/person-4.png",
    email: "aisha@lexia.design",
    linkedin: "https://www.linkedin.com/company/lexia",
    slug: "aisha-putri",
  },
  {
    name: "Daniel Hartono",
    role: "Digital Project Manager",
    bio: "Daniel orchestrates our web projects with precision. His articles cover agile methodologies, digital project management, and ensuring successful project delivery.",
    image: "/team/person-3.png",
    email: "daniel@lexia.design",
    linkedin: "https://www.linkedin.com/company/lexia",
    slug: "daniel-hartono",
  },
]
