export const projectsData = [
  {
    id: "1",
    slug: "minimalist-villa",
    title: "Minimalist Villa",
    description: "A modern minimalist villa with clean lines and open spaces, designed for luxury living.",
    year: 2023,
    location: "Bali, Indonesia",
    category: "Residential",
    coverImage: "/portfolio/house-1.png",
    images: ["/portfolio/house-1-detail-1.png", "/portfolio/house-1-detail-2.png", "/portfolio/house-1-detail-3.png"],
    features: [
      "5 bedrooms",
      "6 bathrooms",
      "Infinity pool",
      "Home theater",
      "Smart home technology",
      "Sustainable materials",
    ],
    area: "450 sq.m",
    client: "Private Client",
    architects: ["Sarah Johnson", "Michael Chen"],
    hasVirtualTour: true,
    virtualTourImage: "/vr/minimalist-villa-360.png",
  },
  {
    id: "2",
    slug: "urban-apartment-complex",
    title: "Urban Apartment Complex",
    description:
      "A sustainable urban apartment complex designed to maximize space while providing comfort and community.",
    year: 2022,
    location: "Singapore",
    category: "Residential",
    coverImage: "/portfolio/house-2.png",
    images: ["/portfolio/house-2-detail-1.png", "/portfolio/house-2-detail-2.png", "/portfolio/house-2-detail-3.png"],
    features: [
      "120 units",
      "Rooftop garden",
      "Community spaces",
      "Fitness center",
      "Rainwater harvesting",
      "Solar panels",
    ],
    area: "12,000 sq.m",
    client: "Urban Development Corp.",
    architects: ["David Wong", "Emma Patel"],
    hasVirtualTour: false,
  },
  {
    id: "3",
    slug: "eco-friendly-office",
    title: "Eco-Friendly Office Building",
    description: "A LEED Platinum certified office building that prioritizes sustainability and employee wellbeing.",
    year: 2021,
    location: "Jakarta, Indonesia",
    category: "Commercial",
    coverImage: "/portfolio/house-3.png",
    images: ["/portfolio/house-3.png"],
    features: [
      "Zero net energy",
      "Green roof",
      "Natural ventilation",
      "Daylight harvesting",
      "Recycled materials",
      "Bike storage",
    ],
    area: "8,500 sq.m",
    client: "GreenTech Innovations",
    architects: ["Sarah Johnson", "Robert Lee"],
    hasVirtualTour: false,
  },
  {
    id: "4",
    slug: "coastal-retreat",
    title: "Coastal Retreat",
    description: "A luxurious beachfront home designed to withstand coastal conditions while embracing the ocean view.",
    year: 2022,
    location: "Lombok, Indonesia",
    category: "Residential",
    coverImage: "/portfolio/house-4.png",
    images: ["/portfolio/house-4.png"],
    features: [
      "4 bedrooms",
      "Oceanfront terrace",
      "Saltwater pool",
      "Outdoor kitchen",
      "Hurricane-resistant design",
      "Private beach access",
    ],
    area: "380 sq.m",
    client: "Private Client",
    architects: ["Emma Patel", "Michael Chen"],
    hasVirtualTour: false,
  },
  {
    id: "5",
    slug: "boutique-hotel",
    title: "Boutique Hotel",
    description: "A charming boutique hotel that blends local cultural elements with modern luxury.",
    year: 2020,
    location: "Yogyakarta, Indonesia",
    category: "Commercial",
    coverImage: "/portfolio/house-5.png",
    images: ["/portfolio/house-5.png"],
    features: [
      "24 rooms",
      "Rooftop restaurant",
      "Spa facilities",
      "Courtyard garden",
      "Local artisan furnishings",
      "Cultural experiences",
    ],
    area: "1,800 sq.m",
    client: "Heritage Hospitality Group",
    architects: ["David Wong", "Lisa Hartono"],
    hasVirtualTour: false,
  },
  {
    id: "6",
    slug: "mountain-cabin",
    title: "Mountain Cabin",
    description: "A cozy yet modern cabin designed to maximize views while providing shelter in extreme conditions.",
    year: 2021,
    location: "Mount Bromo, Indonesia",
    category: "Residential",
    coverImage: "/portfolio/house-6.png",
    images: ["/portfolio/house-6.png"],
    features: [
      "3 bedrooms",
      "Panoramic windows",
      "Thermal insulation",
      "Wood-burning fireplace",
      "Solar power system",
      "Rainwater collection",
    ],
    area: "210 sq.m",
    client: "Private Client",
    architects: ["Robert Lee", "Emma Patel"],
    hasVirtualTour: false,
  },
  {
    id: "7",
    slug: "urban-renewal-project",
    title: "Urban Renewal Project",
    description: "A community-focused redevelopment project that transformed an abandoned factory into a vibrant hub.",
    year: 2019,
    location: "Surabaya, Indonesia",
    category: "Commercial",
    coverImage: "/portfolio/house-7.png",
    images: ["/portfolio/house-7.png"],
    features: [
      "Mixed-use spaces",
      "Public plaza",
      "Art installations",
      "Farmers market",
      "Co-working spaces",
      "Adaptive reuse",
    ],
    area: "15,000 sq.m",
    client: "Surabaya City Development",
    architects: ["Lisa Hartono", "David Wong"],
    hasVirtualTour: false,
  },
  {
    id: "8",
    slug: "sustainable-school",
    title: "Sustainable School Campus",
    description: "An innovative educational facility designed to inspire learning and environmental consciousness.",
    year: 2020,
    location: "Bandung, Indonesia",
    category: "Institutional",
    coverImage: "/portfolio/house-8.png",
    images: ["/portfolio/house-8.png"],
    features: [
      "30 classrooms",
      "Science labs",
      "Outdoor learning spaces",
      "Sports facilities",
      "Edible gardens",
      "Renewable energy systems",
    ],
    area: "12,500 sq.m",
    client: "Future Education Foundation",
    architects: ["Michael Chen", "Sarah Johnson"],
    hasVirtualTour: false,
  },
  {
    id: "9",
    slug: "wellness-center",
    title: "Wellness Center",
    description: "A holistic wellness center that promotes health through thoughtful design and natural elements.",
    year: 2023,
    location: "Ubud, Bali",
    category: "Healthcare",
    coverImage: "/portfolio/house-9.png",
    images: ["/portfolio/house-9.png"],
    features: [
      "Yoga studios",
      "Meditation spaces",
      "Treatment rooms",
      "Thermal pools",
      "Organic café",
      "Healing gardens",
    ],
    area: "3,200 sq.m",
    client: "Harmony Wellness Group",
    architects: ["Emma Patel", "Lisa Hartono"],
    hasVirtualTour: false,
  },
]
